# Generated by Django 5.1.2 on 2025-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
