# Generated by Django 5.1.2 on 2025-08-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_deadline',
        ),
    ]
