# Generated by Django 5.1.2 on 2025-08-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_payment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_url',
            field=models.URLField(blank=True, help_text='Stripe checkout session URL for pending payments', max_length=500, null=True),
        ),
    ]
