# Generated by Django 5.1.2 on 2025-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcolor_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='hex_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
