# Generated by Django 5.1.2 on 2025-08-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
