# Generated by Django 5.1.2 on 2025-08-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
        ('payments', '0003_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'refunded')), fields=('order',), name='unique_refund_per_order'),
        ),
    ]
