# Generated by Django 5.1.2 on 2025-08-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
        ('payments', '0004_paymenttransaction_unique_refund_per_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymenttransaction',
            name='unique_refund_per_order',
        ),
        migrations.AlterUniqueTogether(
            name='paymenttransaction',
            unique_together={('order', 'stripe_checkout_id')},
        ),
    ]
