# Generated by Django 5.1.2 on 2025-07-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('VN', 'Vietnam'), ('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('AU', 'Australia'), ('SG', 'Singapore'), ('JP', 'Japan')], default='VN', max_length=100),
        ),
    ]
